#!/usr/bin/env node

'use strict';
let Database = require('better-sqlite3')
let quote = require('shell-quote').quote
let Finder = require('./lib/finder')

let argv = Finder.argv_parse(process.argv.slice(2))
if (!(argv.db && argv._.length)) {
    console.error(`Usage: --db file.sqlite3 QUERY\n${Finder.help}`)
    process.exitCode = 1
} else {
    let finder = new Finder(new Database(argv.db))
    console.log(finder.find(quote(process.argv.slice(2))))
}
