#!/bin/sh

# sql quote
q() { echo "'`echo "$1" | sed "s/'/''/g"`'"; }

# metatags csv type
metatags() {
    local IFS=,
    for val in $1; do
	echo "INSERT INTO metatags(file,type,name) VALUES (`q "$file"`, '$2', `q "$val"`);"
    done
}

markdown_to_html='pandoc -f markdown-smart-tex_math_dollars -t html5'
html_to_text='w3m -T text/html -dump -I UTF-8 -O UTF-8 -no-graph'

__dir=$(dirname "$(readlink -f "$0")")
eval "`"$__dir/frontmatter" "$1"`" '
[ $? -eq 0 ] || exit 1'

body=`echo "$title" "$body" | $markdown_to_html | $html_to_text`
file=`basename "$1"`

echo "INSERT INTO fts(file,title,date,body) VALUES (`q "$file"`, `q "$title"`, `q "$date"`, `q "$body"`);"
metatags "$authors" author
metatags "$tags" tag
